transaction fee statistics-backend api
nervosnetwork/ckb-explorer pull request #1162
Opened 2023-02-02 02:01 UTC by iamyates

related issues: 
- (for this PR) backend:  https://github.com/Magickbase/ckb-explorer-public-issues/issues/155

added an API to get the statistic data about transaction fees.

# usage: 

api official doc:  https://www.apifox.cn/apidoc/project-962207/api-58580603

GET: http://47.113.186.173:3050/api/v2/statistics/transaction_fees

result: 

```
{
    "transaction_fee_rates": [
        {
            "id": 17539378,
            "timestamp": 1673669693,
            "fee_rate": 0,
            "confirmation_time": 11
        },
        {
            "id": 17539377,
            "timestamp": 1673669693,
            "fee_rate": 1.1074197120708749,
            "confirmation_time": 12
        },
        {
            "id": 17539376,
            "timestamp": 1673669693,
            "fee_rate": 1.1074197120708749,
            "confirmation_time": 13
        }
    ],
    "pending_transaction_fee_rates": [
        {
            "id": 2,
            "fee_rate": 0
        },
        {
            "id": 1,
            "fee_rate": 0
        }
    ],
    "last_n_days_transaction_fee_rates": [
        {
            "date": "2023-01-14T00:00:00.000+00:00",
            "fee_rate": "5.544518608636935261016627"
        },
        {
            "date": "2023-01-13T00:00:00.000+00:00",
            "fee_rate": "7.191871857757579661659231"
        },
        {
            "date": "2023-01-12T00:00:00.000+00:00",
            "fee_rate": "5.489535279531177736769346"
        },
        {
            "date": "2023-01-11T00:00:00.000+00:00",
            "fee_rate": "9.303205754865450675405469"
        },
        {
            "date": "2023-01-10T00:00:00.000+00:00",
            "fee_rate": "3.1925939557464105920828024"
        },
        {
            "date": "2023-01-09T00:00:00.000+00:00",
            "fee_rate": "2.2412663196970118725147738"
        },
        {
            "date": "2023-01-08T00:00:00.000+00:00",
            "fee_rate": "4.512429694415110836790901"
        }
    ]
}
```

2023-02-08 09:37 UTC, Keith-CY commented
Conflicted

2023-02-13 06:59 UTC, ShiningRay requested changes

2023-02-13 06:59 UTC, ShiningRay commented on app/models/block.rb
> +      group by 1 order by 1 desc}
why add this?

2023-02-13 06:59 UTC, ShiningRay commented on app/models/ckb_sync/new_node_data_processor.rb
> +        attrs[:cycles] = tx_index > 0 ? cycles[tx_index - 1]&.hex : nil
merge error

2023-02-13 13:59 UTC, ShiningRay approved these changes

2023-02-13 16:43 UTC, merged