feat: reduce ckb transactions export as csv n+1 querys
nervosnetwork/ckb-explorer pull request #1301
Opened 2023-06-05 07:29 UTC by rabbitz

2023-06-05 07:46 UTC, zmcNotafraid commented
Needs to add test.

2023-06-06 05:12 UTC, rabbitz commented
https://github.com/nervosnetwork/ckb-explorer/blob/develop/test/test_helper.rb#L176

The timestamp parameter in the `fake_node_block` method is the millisecond value `1557482351075`, but https://github.com/nervosnetwork/ckb-explorer/blob/develop/test/factories/block.rb#L9 The timestamp of the generated block is seconds, `Block.recent.first` Always take the first record, and the corresponding mining_infos value is empty, resulting in an error in https://github.com/nervosnetwork/ckb-explorer/blob/develop/app/jobs/revert_block_job.rb#L122

@zmcNotafraid @ShiningRay

2023-06-06 05:50 UTC, ShiningRay commented
I suggest extract the CSV generation code into a separate job class.
So we can reuse them later, or refactor to support background generation.

2023-06-06 07:36 UTC, zmcNotafraid requested changes

2023-06-06 07:36 UTC, zmcNotafraid commented on test/factories/block.rb
> +    timestamp { Faker::Time.between(from: 2.days.ago, to: Date.today).to_i * 1000 }
Here should use a fixed value. You can get number 10 block's timestamp from vcr files. It's 1570197479041.

2023-06-06 07:46 UTC, zmcNotafraid approved these changes

2023-06-06 08:22 UTC, ShiningRay requested changes

2023-06-06 08:22 UTC, ShiningRay commented on app/jobs/export_address_transactions_job.rb
> +    Rails.cache.realize(args.values, race_condition_ttl: 1.minute) do
don't use `Rails.cache.realize`

2023-06-06 08:29 UTC, ShiningRay approved these changes

2023-06-06 09:24 UTC, merged