refactor: backend epoch statistics
nervosnetwork/ckb-explorer pull request #1313
Opened 2023-06-15 04:14 UTC by rabbitz

2023-06-26 03:03 UTC, zmcNotafraid commented on app/workers/charts/epoch_statistic.rb
> +      epoch_statistic = ::EpochStatistic.find_or_create_by(epoch_number: target_epoch_number)
I found these code and next `fill_epoch_statistic `method code  were same.So maybe we can replace  `Charts::EpochStatisticGenerator` 's code with your code.

2023-06-29 08:41 UTC, ShiningRay requested changes

2023-06-29 08:41 UTC, ShiningRay commented on config/schedule.yml
> -chart_forked_event_processor:
This schedule.yml is deprecated. Please set cron job in `scheduler.rb`

2023-06-29 09:59 UTC, ShiningRay approved these changes

2023-06-29 10:00 UTC, ShiningRay requested changes

2023-06-29 10:07 UTC, ShiningRay approved these changes

2023-06-29 10:33 UTC, merged