Fix the memory leak in cell data callback
nervosnetwork/ckb-explorer pull request #1318
Opened 2023-06-21 14:33 UTC by ShiningRay

and fix the unit test for dao events

2023-06-25 01:20 UTC, rabbitz commented on app/models/cell_output.rb
> +  def dao
duplicate dao methods

2023-06-26 02:51 UTC, zmcNotafraid requested changes

2023-06-26 02:51 UTC, zmcNotafraid commented on app/models/ckb_sync/new_node_data_processor.rb
> +        CellOutput.create_or_find_by! cell_outputs_attributes
create_or_find_by! needs to add unique index to cell_outputs table.
https://apidock.com/rails/v6.0.0/ActiveRecord/Relation/create_or_find_by

2023-06-28 08:04 UTC, zmcNotafraid approved these changes

2023-06-29 13:40 UTC, merged