change average_block_time api to return full records
nervosnetwork/ckb-explorer pull request #905
Opened 2022-04-07 17:59 UTC by ShiningRay

merge average_block_time from daily_statistics table to return full records

2022-04-08 08:18 UTC, Keith-CY commented
CI failed https://github.com/nervosnetwork/ckb-explorer/runs/5880133367?check_suite_focus=true#step:6:1288

2022-04-15 06:21 UTC, zmcNotafraid requested changes

2022-04-15 06:21 UTC, zmcNotafraid commented on app/models/block.rb
> +    Address.find_by(address_hash: miner_hash, address_hash_crc: CkbUtils.generate_crc32(miner_hash))
这里加这个是为了什么

2022-04-15 06:21 UTC, zmcNotafraid commented on app/models/ckb_sync/new_node_data_processor.rb
> +      txs = CkbTransaction.insert_all!(ckb_transactions_attributes, returning: %w(id tx_hash created_at))
交易不可能是nil 吧，怎么都会有个矿工的交易吧

2022-04-15 06:22 UTC, ShiningRay commented on Gemfile
> +gem "pagy"
kaminari的count语法太复杂了，容易产生性能问题

2022-04-15 06:23 UTC, ShiningRay commented on app/models/block.rb
> +    Address.find_by(address_hash: miner_hash, address_hash_crc: CkbUtils.generate_crc32(miner_hash))
hash，也就是地址，不适合使用普通索引，普通索引是b+tree，是一种有顺序的索引，对于这种字符串效率并不高
之前俊达通过增加crc字段，把字符串从某种程度上变成了hash索引，用整数缩小查找范围

2022-04-18 03:12 UTC, Keith-CY commented
CI failed https://github.com/nervosnetwork/ckb-explorer/runs/6046229035?check_suite_focus=true#step:6:1288

2022-04-18 11:44 UTC, zmcNotafraid approved these changes

2022-04-18 14:00 UTC, merged